site_name: 喜马拉雅Ads
  #site_url: https://xmlyads.github.io
theme:
  name: material
  language: zh
  palette:
    scheme: slate
    primary: deep orange
    accent: indigo

plugins:
  - search

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - 关于我们: index.md
  - Marketing API接入文档: 
    - 快速开始:
      - 从这里开始: mktapi/start.md
      - 刷新Access_Token: mktapi/accessToken.md
      - 授权信息查询: mktapi/queryDevInfo.md
    - 广告投放:
      - 广告计划查询: mktapi/queryCampaign.md
      - 广告单元查询: mktapi/queryAd.md
      - 广告创意查询: mktapi/queryCreative.md
      - 广告素材查询: mktapi/querySegment.md
    - 数据报表:
      - 数据报表查询: mktapi/statement.md
      - 数据报表域查询: mktapi/queryStatementField.md
    - 系统管理:
      - 枚举信息查询:  mktapi/queryEnum.md
      - 枚举信息精确查询: mktapi/queryOneEnum.md
      - 定向信息查询: mktapi/queryTarget.md
      - 账户权限申请: mktapi/approvalLanch.md
      - 错误码: mktapi/errorCode.md
      - 版本说明: mktapi/versionCode.md
    - 注册: mktapi/reg.md
    - 广告实体: mktapi/entities.md
  - About: about.md
  - Example: example.md
