site_name: 喜马拉雅Ads
  #site_url: https://xmlyads.github.io
theme:
  name: material
  language: zh
  palette:
    scheme: slate
    primary: deep orange
    accent: indigo

plugins:
  - search

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Home: index.md
  - MarketingAPI: mktapi.md
  - About: about.md
  - Example: example.md
